{% set name = "depht" %}
{% set version = "1.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/depht-{{ version }}.tar.gz
  # sha256: f8a58e76e363ade42b03b82ede2609eef02c6f4921850faf5f5ac724838a9aaf

build:
  number: 0
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python ==3.9
    - pip

  run:
    - aragorn ~=1.2.38
    - blast ==2.9.0
    - clustalo ~=1.2.4
    - hhsuite ~=3.3.0
    - mmseqs2 ==13.45111
    - prodigal ~=2.6.3
    - python ~=3.9.0
    - biopython >=1.78
    - bitarray ~=2.0.1
    - bokeh ~=2.4.2 
    - dna_features_viewer ~=3.1.0
    - matplotlib-base ~=3.4.1
    - numpy ~=1.22.3
    - pandas ~=1.4.2
    - phamclust ~=0.1.2
    - plotly ~=5.1.0
    - pretty_html_table ~=0.9.10
    - python-kaleido ~=0.2.1
    - scipy ~=1.7.0

test:
  imports:
    - depht
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chg60/DEPhT
  summary: Discovery and Extraction of Phages Tool
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - laa89 
    - chg60
